# XXLJOB参数配置
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://192.168.31.234:8093/xxl-job-admin
    executor:
      appname: stock-job-executor
      address:
      ip: 192.168.31.234
      port: 7979
      logpath: ./logs
      logretentiondays: 30
logging:
  config: classpath:logback.xml


